import localFont from "next/font/local";
import "./globals.css";
import Navber from "./Components/shared/Navber";
import Footer from "./Components/shared/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="jusbuy">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="max-w-7xl m-auto">
          <Navber></Navber>
          {children}
          <Footer></Footer>
        </div>

      
      </body>
    </html>
  );
}
